### PR TITLE
WIP: Extend assertion_operator with ``operator:rule`` syntax

### PR DESCRIPTION
**Pull request by robinmatz**
Hi there!

This PR addresses [Issue 34](https://github.com/MarketSquare/AssertionEngine/issues/34).

I have added an additional argument to the verify_assertion function: ``collapse_spaces``, identical to ``collapse_spaces`` in [BuiltIn Library](https://github.com/robotframework/robotframework/blob/master/src/robot/libraries/BuiltIn.py#L664).

It is optional and defaults to ``False``. If set to ``True``, assertions will be performed with normalized white spaces. Additionally, html's ``&nbsp`` (\xA0) and normal space (\x20) will be treated the same.

Issue 34 also requests two additional flags: ``strip_spaces`` and ``ignore_case``. Should these be included in this pull request?

Kind regards,
Robin

### CODE REVIEW

**Comment by aaltat** [comment]
But the error with CI does looks something which is not caused by this PR.

**Comment by robinmatz** [comment]
The cause seems to be missing dependencies for Black that result from upgrade to Python 3.9.8. According to [this post](https://stackoverflow.com/questions/69912264/python-3-9-8-fails-using-black-and-importing-typed-ast-ast3) on Stackoverflow, updating to Black 21.10b will solve the issue.

**Comment by aaltat** [comment]
I updated all the deps in #36. Most likely for you it is easiest to revert changes in  fd8d159 and fetch update from upstream.

**Comment by aaltat** [comment]
I have been thinking about the name space and moving to the side that enhancing assertion operator is the better way to go. Would you be interested to move you PR in that direction.

**Comment by robinmatz** [comment]
Hi @aaltat I am not sure I understand correctly. Could you expand your proposal?

**Comment by aaltat** [comment]
Now that I see your code, I understand this is new argument in the keyword space. In practice it needs changes in all the keywords which uses AsserstionEngine module. Example when using [Get Text](https://marketsquare.github.io/robotframework-browser/Browser.html#Get%20Text) it looks something like: 

`Get Text    id=important    ==    Important`.  

But after this change and how it is now coded, Get Text usage would change to: 

`Get Text    id=important    ==    Important text    collapse_spaces=True` 

Which is not very clean and readable in my mind. Also in the future, if there is enhancements it means adding new arguments, which will mess the keyword argument space even more. Also adding new arguments needs work from upstream projects.

Other way that I have been thinking would the "collapse space" operation be included in the assertion operator. Example now we have operators like, `equal` or `contains`, but could we enhance the syntax. Something like `equal:collapse space` or `equal;collapse space`. Then in keyword level usage would look like this: 

`Get Text    id=important    equal:collapse space    Important text`.

Also the advantage of enhancing assertion operator is that it does not requires changes in the upstream. People get the changes when they update assertion engine. Also it is zero code change for the upstream projects to integrate the change in their projects.

From this project point of view, it needs some more work, but should not be overly complicated.

**Comment by robinmatz** [comment]
Hi @aaltat , I gave this a try and added another AssertionOperator, ``equal;normalize spaces``. Note that I changed from collapse spaces to normalize spaces. I think it is a better fit for marking that this extension also handles different types of white spaces.

I marked this PR as a work in progress, since a few more changes will likely be necessary.

Let me know if you think if I am going in the right direction.

**Comment by aaltat** [comment]
I see where you going with the PR. Have you tough an another way, because this is not very flexible way. If one assumes that in future there will be more those formatting rules and there is need to apply rules  in multiple different assertions, then code need to define each combination of the rules and assertions.

I was more thinking to a direction where assertion operator syntax would be extended: `operator:rule`. Where `operator` is one of the current assertions operators, like `equal`. The rule defines what is done for the object, before the assertion is applied. In this case it would be `substitute space`. But `substitute space` rule should work with other assertion operators, example `contains` or `starts`. In practice combinations like `equal:substitute space`, `should be:substitute space`, `should not be:substitute space`, `contains:substitute space`, `not contains:substitute space`, `starts:substitute space`, `should start with:substitute space`, `ends:substitute space`, `should end with:substitute space` and `matches:substitute space` are at least  possible combinations. 

But I am not sure is where I am aiming doable at all. Let me think about it for a while.

**Comment by robinmatz** [comment]
Hi @aaltat , I tried to come up with a solution that would allow more flexibility.

What I tried to do is to allow the parameter ``assertion_operator`` of the ``verify_assertion`` function to also take in a string in the format ``operator:rule``. There can actually be multiple rules like ``operator:rule1:rule2:ruleN``.

This string is passed to a new function ``get_operators_and_rules``, that will return an ``AssertionOperator`` object as well as a list of rules.

Each rules will be applied to ``value`` and ``expected`` in the ``apply_rules`` function. After that, assertions are performed.

While this approach works, and provides the option to extend with more rules, there is one downside:
In order for this to work, type hinting for the ``assertion_operator`` parameter has to be changed from ``[Optional[AssertionOperator] = None`` to ``[Optional[Union[AssertionOperator, str]]``. Not changing this won't cause AssertionEngine to break. So upstream projects that do not adapt won't face issues. However, they will also not be able to use the new syntax.

I know this is not the optimal solution, but I have yet not come up with a solution that would not cause major changes in the project structure.

Let me know what you think, or if you have come up with another approach.

Regards,
Robin

**Comment by robinmatz** [comment]
Hey,

just checking if there are any new ideas or feedback.

**Comment by aaltat** [comment]
I might have some ideas but I need to do some experiments first.

**Comment by aaltat** [comment]
I have idea for applying rules in #40 Basically it generates AssertionOperator from different sources and uses few logic steps to restore the original operator. But did I get your idea correctly for the rule: https://github.com/MarketSquare/AssertionEngine/pull/40/files#diff-ae082ff59a5fceafe1ab2261dfffa73a187729b72aae7cc482823eb18b706544

**Comment by robinmatz** [comment]
The approach looks very good.
One thing however. And this might be specific to my use case. `_normalize_spaces` does two things: Normalizing spaces and then stripping leading and trailing spaces.

In our use case, we validate element's text on the web page against database fields. 
The database fields do actually contain leading or trailing white space in many cases. This would result in the following workaround:

```
Get Text     id=some_field     validate::normalize_spaces     actual=='${database_field}'.strip()
```

as opposed to

```
Get Text    id=some_field    equal::normalize_spaces     ${database_field}
```

if we removed the strip() at the end of `_normalize_spaces`.

This is not a major impediment, and the above workaround is still way better than my current one.

However, we should also consider that e.g. BuiltIn separates `normalize_spaces` and `strip_spaces`. And I suppose they considered similar use cases for that design choice.


To me, there are two options we have:
1. We could create two rules ``::normalize_spaces`` and ``::strip_spaces``
2. We could apply `::normalize_space` the way it is right now to both actual and expected value.

**Comment by aaltat** [comment]
1) Yes we could have different rules. But I am not sure is it good option, it will double the string available combination. Also currently it is not possible to apply two rules at the same time. Applying two rules is technically possible, but with more rules it will grow the total number of assertions and therefore it is not good idea. 
2) I am thinking that rules should be applied only to value but not to the expected value..

**Comment by aaltat** [comment]
I am not happy with the solution in #40 
1) When there will be new rules, the number of assertions will explode. 
2) Also as you pointed out, there will be need to apply two or more rules at the same time. 

Because of the above and limitations of RF, something better design need to be created. I did discuss this with other core developers in Browser library side and we came up with different idea. Instead trying to force rule in the keywords arguments, we could define default rules for each keyword. Something like this:
```
Default Transformation    Get Text    normalize spaces::strip spaces    Get Title    normalize spaces
${text} =    Get Text    //div    ==    Some thing    #  Transformation normalize spaces and strip spaces would be applied
${title] =    Get Title    ==    Other    # Transformation normalize spaces  is only applied
```
Also it was suggested that rule should be renamed to transformation. 

It is bad that we it needs new keyword, but it is hard to make this happen without making major backwards incompatible change in the keywords level. Or without exploding the number of assertion operators. 

 What do you think?

**Comment by robinmatz** [comment]
Setting the transformation performed by keywords outside the actual keyword like you showed makes it possible to set them only once instead of repeating ``::normalize_spaces``, etc. every time.

However it sounds like major changes in Browser Library are also required, and it could be that we are overcomplicating things.

I was wondering if we could reconsider some approaches I made in this PR. 

The approach was to split a string like ``operator:rule`` or even `operator:rule1:rule2:ruleN` into an AssertionOperator object as well as a list of rules. These rules will be applied one by one to both actual and expected value before performing the assertion.

One thing I do not like about the current version, however, is that the ``operator:rule`` pattern is interpreted as string. For seamless integration into Browser Library it would be necessary to have it interpreted as AssertionOperator. But I have not yet come up with an idea how.

**Comment by aaltat** [comment]
The implementation in both sides is straight forward. Most likely the easiest option is to create class in AssertionEngine side, which can provide the functionality and the new keyword to library side. Then the new class is inputted to the [PLC](https://github.com/robotframework/PythonLibCore) from browser library and stuff will work out of the box (mostly). It might require some tuning in the Browser library side, but we avoid the biggest obstacles: 1) Changing keywords argument specification in backwards incompatible way 2) Creating too many assertion operators. 

 Creating assertion operators dynamically is not problem, see example [this](https://github.com/MarketSquare/AssertionEngine/pull/40/files#diff-7f6f2f6eda2d7c5b989c197f314c5b616bc9373f67aaf70f223310f055e9bf36R28-R67) but the problem is that there needs to be one operator for each combination. Example if there is three operators and three rules, there will be 27 operators in total. If there six operators and three rules, there will be 216 operators in total. Therefore number grows too big too fast when new operators or rules are added.

**Comment by robinmatz** [comment]
That sounds like you have a concrete plan that we can work with.

Before we start, I would like to convince you again to apply the transformation on both value as well as expected. This for two reasons.

Number 1, which is from my example. There are some database values that also have some spaces in between. 
This would cause the workaround to look like this
```
Get Text    id=some_field     validate::normalize spaces    value==re.sub('\\s+', ' ', '${database_field}').strip()
```
Given the goal of RF to make test automation accessible also to non-devs, I think this might be a little to complated.

Number 2. Consider there will be a rule like `::ignore case`. This rule will only work reliably if the transformation is performed both on value as well as expected, see e.g. the implementation of BuiltIn's `Should Be Equal` used with [ignore case](https://github.com/robotframework/robotframework/blob/297f2cafc198c76aabe637561f1d36fb4f675dee/src/robot/libraries/BuiltIn.py#L606-L608) and [collapse spaces](https://github.com/robotframework/robotframework/blob/297f2cafc198c76aabe637561f1d36fb4f675dee/src/robot/libraries/BuiltIn.py#L612-L614).
<br/>
As for the idea with the new class in AssertionEngine which would be inputted in PLC of Browser Library. Could you expand on that. 
- How would it be called? 
- What properties and methods should this class contain?
- How will it interact with the rest of Browser Library?

**Comment by aaltat** [comment]
I see you point with excepted value, well perhaps we can make it configurable. 

Question from PLC will be easier to ask when I have some code ready for acceptance tests. But PLC is already used by Browser (and few other) library, so all is ready from that side.

**Comment by aaltat** [comment]
Here is an [example](https://github.com/MarketSquare/AssertionEngine/pull/40/files#diff-cde673d88ebf26e79cc8951f63bd62214082896fdee427f5e119bf8049f33a5d) how the rules are used in library side. There is need to modify little bit the code in library side, but it is adding one line and add new argument to `verify_assertion` function call. The down side is that  now using rules/formatters

**Comment by aaltat** [comment]
I need to fix the docs and and think is it good idea to require PLC. Although it should be easy to reverse engineer the code in Formatter for libraries not using PLC.

**Comment by aaltat** [comment]
Closing due #40

**Comment by robinmatz** [comment]
Hey @aaltat , now that the changes are merged, we only need to use `Formatter` in Browser Library, too. I have not found an issue for this in Browser Library yet. I can create one, if you like

**Comment by robinmatz** [comment]
Created https://github.com/MarketSquare/robotframework-browser/issues/1645

**Pull request closed without merging**
